#!/usr/bin/env node
/**
 * Pre-build step: Merges ingested events, generates build metadata,
 * and writes app/events-data.js for the app to import.
 */

const fs = require("fs");
const path = require("path");

const INGESTED_PATH = path.join(__dirname, "..", "data", "events.json");
const LOG_PATH = path.join(__dirname, "..", "data", "pipeline-log.json");
const OUTPUT_PATH = path.join(__dirname, "..", "app", "events-data.js");

const TODAY = new Date().toISOString().split("T")[0];
const BUILD_TIME = new Date().toISOString();

let ingested = [];
if (fs.existsSync(INGESTED_PATH)) {
  try {
    const raw = JSON.parse(fs.readFileSync(INGESTED_PATH, "utf8"));
    const future = raw.filter((e) => e.date >= TODAY);
    const hidden = future.filter((e) => e.status === "hidden");
    ingested = future.filter((e) => e.status !== "hidden");
    console.log(`📅 Loaded ${ingested.length} active events (${raw.length - future.length} expired, ${hidden.length} hidden, filtered out)`);
  } catch (err) {
    console.warn(`⚠ Could not parse ${INGESTED_PATH}: ${err.message}`);
  }
} else {
  console.log("📅 No ingested events found — using seed data only");
}

// Get last pipeline run info
let lastPipeline = null;
if (fs.existsSync(LOG_PATH)) {
  try {
    const log = JSON.parse(fs.readFileSync(LOG_PATH, "utf8"));
    lastPipeline = log.timestamp;
  } catch {}
}

const output = `// AUTO-GENERATED by scripts/prebuild-events.js — do not edit manually
// Built: ${BUILD_TIME}
// Ingested events: ${ingested.length}

export const INGESTED_EVENTS = ${JSON.stringify(ingested, null, 2)};

export const BUILD_META = {
  buildTime: "${BUILD_TIME}",
  lastPipeline: ${lastPipeline ? `"${lastPipeline}"` : "null"},
  eventCount: ${ingested.length},
};

export const dedupeKey = (e) =>
  \`\${(e.title || "").toLowerCase().trim().replace(/[^a-z0-9]/g, "")}|\${e.date}\`;
`;

fs.writeFileSync(OUTPUT_PATH, output);
console.log(`✓ Generated ${OUTPUT_PATH} with ${ingested.length} events (build: ${BUILD_TIME})`);
