#!/usr/bin/env node
/**
 * prebuild-images.js
 * Scans public/images/content/ and generates app/image-manifest.js
 * so the site can auto-discover images by entity slug.
 *
 * Run: node scripts/prebuild-images.js
 * Called automatically during `npm run build`
 */

const fs = require("fs");
const path = require("path");

const CONTENT_DIR = path.join(__dirname, "..", "public", "images", "content");
const OUTPUT = path.join(__dirname, "..", "app", "image-manifest.js");

const CATEGORIES = [
  "neighborhoods",
  "venues",
  "artists",
  "teams",
  "landmarks",
  "categories",
  "hero",
];

const IMAGE_EXTS = new Set([".jpg", ".jpeg", ".png", ".webp"]);

const manifest = {};

for (const cat of CATEGORIES) {
  const catDir = path.join(CONTENT_DIR, cat);
  if (!fs.existsSync(catDir)) continue;

  manifest[cat] = {};

  const entries = fs.readdirSync(catDir);
  for (const entry of entries) {
    const entryPath = path.join(catDir, entry);
    if (!fs.statSync(entryPath).isDirectory()) continue;

    const files = fs
      .readdirSync(entryPath)
      .filter((f) => IMAGE_EXTS.has(path.extname(f).toLowerCase()))
      .sort();

    if (files.length > 0) {
      manifest[cat][entry] = files.map(
        (f) => `/images/content/${cat}/${entry}/${f}`
      );
    }
  }
}

// Generate JS module
const code = `// AUTO-GENERATED by scripts/prebuild-images.js — DO NOT EDIT
// Generated: ${new Date().toISOString()}
// Scanned: public/images/content/

export const IMAGE_MANIFEST = ${JSON.stringify(manifest, null, 2)};

/**
 * Get images for an entity by category and slug.
 * @param {string} category - "neighborhoods", "venues", "artists", "teams", "landmarks"
 * @param {string} slug - kebab-case entity name, e.g. "old-market", "chi-health-center"
 * @returns {string[]} Array of image paths, or empty array
 */
export function getImages(category, slug) {
  return IMAGE_MANIFEST[category]?.[slug] || [];
}

/**
 * Get the hero (first) image for an entity.
 * @returns {string|null} First image path or null
 */
export function getHeroImage(category, slug) {
  const imgs = getImages(category, slug);
  return imgs.length > 0 ? imgs[0] : null;
}

// Quick stats
export const IMAGE_STATS = {
${Object.entries(manifest)
  .map(([cat, entries]) => {
    const totalFiles = Object.values(entries).reduce(
      (sum, files) => sum + files.length,
      0
    );
    return `  ${cat}: { folders: ${Object.keys(entries).length}, files: ${totalFiles} }`;
  })
  .join(",\n")},
};
`;

fs.writeFileSync(OUTPUT, code);

// Print stats
const totalFolders = Object.values(manifest).reduce(
  (sum, cat) => sum + Object.keys(cat).length,
  0
);
const totalFiles = Object.values(manifest).reduce(
  (sum, cat) =>
    sum +
    Object.values(cat).reduce((s, files) => s + files.length, 0),
  0
);

console.log(`Image manifest generated: ${totalFolders} folders, ${totalFiles} files`);
for (const [cat, entries] of Object.entries(manifest)) {
  const files = Object.values(entries).reduce(
    (sum, f) => sum + f.length,
    0
  );
  console.log(`  ${cat}: ${Object.keys(entries).length} folders, ${files} files`);
}
